import type { DogData } from "@/types/dog"

export const DOGS: DogData[] = [
  {
    id: 1,
    type: 'shiba',
    name: '시바견',
    direction: 'right',
    walkHeight: -5,
    speechText: '멍멍!',
  },
  {
    id: 2,
    type: 'fug1',
    name: '불독1',
    direction: 'left',
    walkHeight: 40,
    speechText: '함께 게임해요!',
  },
  {
    id: 3,
    type: 'retriever',
    name: '리트리버',
    direction: 'right',
    walkHeight: 60,
    speechText: '안녕~ 나랑 놀아!',
  },
  {
    id: 4,
    type: 'poodle',
    name: '푸들',
    direction: 'left',
    walkHeight: -10,
    speechText: '즐거운 릴레이!',
  },
  {
    id: 5,
    type: 'chihuahua',
    name: '치와와',
    direction: 'left',
    walkHeight: 30,
    speechText: '왔어? 신나!',
  },
  {
    id: 6,
    type: 'Dachshund',
    name: '닥스훈트',
    direction: 'right',
    walkHeight: 0,
    speechText: '멍멍!',
  },
  {
    id: 7,
    type: 'bichon',
    name: '비숑',
    direction: 'left',
    walkHeight: 10,
    speechText: '즐거운 릴레이!',
  },
] 
